# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Run Flask App (for 10 seconds)
      run: |
        tmux new -d -s flask_session "python app.py"
        tmux ls
    - name: Setup virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Restart Flask App with PM2
      run: |
        if pm2 list | grep -q "flask-app"; then
          pm2 restart flask-app
        else
          pm2 start app.py --name flask-app --interpreter ./venv/bin/python
        fi
        pm2 save

